Feature/documentation
CourseDesign/conev-sync pull request #19
Opened 2020-09-07 14:19 UTC by angello10

## 관련 이슈
Close #11

## TODO
- [ ] 테스트 코드 작성
- [ ] 비즈니스 로직 작성
- [ ] 로컬 환경에서 테스트

## Reference

2020-09-08 00:03 UTC, siyual-park requested changes
package.json 에도 잘못된 정보들이 좀 남아 있어서 그부분 수정 부탁드려요!

2020-09-09 00:54 UTC, siyual-park commented
https://github.com/zeke/semantic-pull-requests
PR name convention 통일 부탁드려요

2020-09-09 00:57 UTC, siyual-park commented on README.md
> +    import {ConfigBuilder, JsonSource} from 'conev-sync';
``` typescript
import {ConfigBuilder, JsonSource} from 'conev-sync';
```

같이 해주시면 좋을거 같아요. 들여쓰기가 조금식 다른것 같아서 통일해주시면 좋을거 같아요

2020-09-09 08:26 UTC, angello10 commented on README.md
> +    import {ConfigBuilder, JsonSource} from 'conev-sync';
여러 에디터에서 작업하다 보니 인덴팅이 섞였었나 보네요. 수정했습니다.

2020-09-09 08:41 UTC, siyual-park commented on README.md
> +    import {ConfigBuilder, JsonSource} from 'conev-sync';
markdown의 code formating을 사용해서 작성 부탁드려요 지금은 그냥 text로 들어간것 같아요

2020-09-09 08:55 UTC, JellyBrick approved these changes

2020-09-11 01:19 UTC, siyual-park approved these changes

2020-09-11 01:19 UTC, merged